baseurl: ""
url: "bousis.github.io"
permalink: /:categories/:year/:month/:day/:title.html

# For inline code

# Site settings
title: Quinlan Lab @ UU
email: aaronquinlan@gmail.com
description: "The Quinlan Laboratory at The University of Utah."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: DD1144
  secondary: DD1144
  secondary-dark: 737373

category-list: [software, blog]

# Team names, titles and social links
people:
- name: Aaron Quinlan
  pic: aaron
  position: Principal Investigator
  social:
    - title: github
      url: https://github.com/arq5x
    - title: twitter
      url: https://twitter.com/aaronquinlan
    - title: graduation-cap
      url: https://scholar.google.com/citations?user=QwVZZKsAAAAJ&hl=en&oi=ao
    - title: file-text-o
      url: https://github.com/arq5x/vitae/raw/master/quinlan.cv.pdf

- name: Brent Pedersen
  pic: brent
  position: Senior Programmer
  social:
    - title: github
      url: https://github.com/brentp
    - title: graduation-cap
      url: https://scholar.google.com/citations?user=tDf0VkUAAAAJ&hl=en&oi=ao
    - title: twitter
      url: https://twitter.com/brent_p

- name: Amelia Wallace
  pic: wallace.small
  position: Postdoctoral Research Associate
  social:
    - title: github
      url: https://github.com/adw222

- name: Meenal Gupta
  pic: meenal.small
  position: Sr. Research Scientist
  social:
    - title: github
      url: https://github.com/Meenal002
    - title: graduation-cap
      url: https://scholar.google.com/citations?user=ZGkMQ5AAAAAJ&hl=en&oi=ao

- name: Tom Nicholas
  pic: nicholas
  position: Sr. Research Scientist
  social:
    - title: twitter
      url: https://twitter.com/FakeDrTom

- name: Peter McHale
  pic: mchale.small
  position: Sr. Analyst/Programmer
  social:
    - title: github
      url: https://github.com/petermchale
    - title: graduation-cap
      url: https://scholar.google.com/citations?user=YEgElgMAAAAJ&hl=en

- name: Hao Hou
  pic: hao
  position: Programmer / Staff Scientist
  social:
    - title: github
      url: https://github.com/38

- name: Joe Brown
  pic: joe
  position: Programmer / Staff Scientist
  social:
    - title: github
      url: https://github.com/brwnj
    - title: twitter
      url: https://twitter.com/brwn_j


- name: Tom Sasani
  pic: sasani
  position: Graduate Student
  bio:
  >
    Currently, my research is focused on understanding the landscape
    of de novo mutation in the human genome. Using deep sequencing data
    from large, multi-generational pedigrees, I am developing an accurate
    estimate of the human mutation rate, and assessing the influence of
    relevant molecular processes (recombination, DNA replication, etc.)
    on this rate. Previously, as part of a collaboration with Nels Elde’s
    lab, I used the Oxford Nanopore sequencing platform to investigate
    adaptive structural variation in evolving poxvirus genomes.
  social:
    - title: github
      url: https://github.com/tomsasani

- name: Stephanie Kravitz
  pic: kravitz
  position: Graduate Student
  bio:
  >
    My research is to understand the role and extent of allele-specific
    expression in human tissues. My goal is to inform how genetic variation
    leads to phenotypic heterogeneity and disease, with a focus on neurological
    disorders and potential applications for personalized medicine. This research
    combines statistical modeling of large, publicly available, genomics datasets
    as well as wet lab approaches such as histology, imaging, and single cell
    genomics experiments.
  social:
    - title: github
      url: https://github.com/snkravitz
    - title: twitter
      url: https://twitter.com/snkravitz

- name: Jonathan Belyeu
  pic: belyeu2
  position: Graduate Student
  bio:
  >
    I’m researching structural variation in human genomes, motivated
    by the unique challenges arising from the complexity of finding
    chromosomal rearrangements with short read sequencing technologies.
    I’m developing computational approaches to more accurately discover
    structural variation, especially in repetitive regions of the genome.
    I am devising new visualization techniques and approaches to identify
    false positive structural variant calls that come from existing software.
    I am also investigating de novo structural variation and working on
    better methods to identify these new structural variants in families,
    which will empower research into spontaneous genetic disease.
  social:
    - title: github
      url: https://github.com/jbelyeu

- name: Michael Cormier
  pic: cormier
  position: Graduate Student
  bio:
  >
      TODO
  social:
    - title: github
      url: https://github.com/mikecormier

- name: Harriet Dashnow
  pic: harriet
  position: Postdoctoral Scientist
  bio:
  >
  social:
    - title: github
      url: https://github.com/hdashnow
    - title: twitter
      url: https://twitter.com/hdashnow

- name: Simone Longo
  pic: simone
  position: Graduate Student
  bio:
  >
  social:
    - title: github
      url: https://github.com/SpacemanSpiff7


# Alumni
alumni:
- name: Brian Lohman
  pic: lohman.small
  position: Postdoctoral Research Associate
  social:
    - title: github
      url: https://github.com/BrianLohman
    - title: graduation-cap
      url: https://scholar.google.com/citations?user=3EZjoXkAAAAJ&hl=en&oi=ao

- name: Ryan Layer
  pic: ryan
  position: Assistant Professor at CU-Boulder
  social:
    - title: github
      url: https://github.com/ryanlayer
    - title: graduation-cap
      url: https://scholar.google.com/citations?user=BE2DZ_kAAAAJ&hl=en&oi=ao
    - title: twitter
      url: https://twitter.com/ryanlayer

- name: Jim Havrilla
  pic: jim
  position: Graduate Student
  bio:
  >
    By integrating population scale datasets of genetic variation,
    my research seeks to identify highly constrained coding regions
    (CCRs) in the human genome. My central hypithesis is that these
    critical coding regions will be devoid of genetic variation in
    healthy individuals because mutations therein will lead to severe
    developmental phenotypes and, in the most extreme case, embryonic
    lethality. I am also developing new analysis and visualization
    tools to prioritize clinical variants based on their predicted
    pathogenicity.
  social:
    - title: github
      url: https://github.com/jimhavrilla
    - title: twitter
      url: https://twitter.com/jim_havrilla

- name: Uma Paila
  pic: uma
  position: Postdoctoral Scientist
  social:
    - title: github
      url: https://github.com/udp3f

- name: Neil Kindlon
  pic: neil
  position: Programmer
  social:
    - title: github
      url: https://github.com/nkindlon

- name: John Kubinski
  pic: john
  position: Undergraduate Researcher

- name: Phanwadee Sinthong
  pic: gift
  position: Undergraduate Researcher

- name: Nathan Wilkinson
  pic: wilkinson
  position: Undergraduate Student
  social:
    - title: github
      url: https://github.com/nathanwilk7




# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/aaronquinlan
  - title: github
    url: http://github.com/quinlan-lab
  - title: google
    url: https://scholar.google.com/citations?user=QwVZZKsAAAAJ&hl=en
